/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_denuarchirinos;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Denuar
 */
public class Ventana extends javax.swing.JFrame {
    String pass, pass2 = "";
    int llave, estado=0;
    ArrayList <String> mundos = new ArrayList();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();        
        jd_login1.setVisible(true);
//        jTabbedPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login1 = new javax.swing.JDialog();
        jp_login1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_llave = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jd_login2 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        txt_user1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_pass2 = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_ayuda = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_mundo = new javax.swing.JTextField();
        btn_guardarMundo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_mundos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_nombreCriatura = new javax.swing.JTextField();
        txt_energia = new javax.swing.JTextField();
        txt_años = new javax.swing.JTextField();
        txt_region = new javax.swing.JTextField();
        txt_especies = new javax.swing.JTextField();
        btn_guardarCriatura = new javax.swing.JButton();
        rb_1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_1 = new javax.swing.JTextArea();
        btn_buscarMundo = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cb_mundos1 = new javax.swing.JComboBox<>();
        btn_eliminarCriatura = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cb_mundos2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_nombreCriatura1 = new javax.swing.JTextField();
        txt_energia1 = new javax.swing.JTextField();
        txt_años1 = new javax.swing.JTextField();
        txt_region1 = new javax.swing.JTextField();
        txt_especies1 = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        rb_2 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();

        jd_login1.setMinimumSize(new java.awt.Dimension(720, 520));

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        txt_user.setEditable(false);
        txt_user.setText("xxxGranAtuinxxx");

        btn_guardar.setText("guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Llave");

        javax.swing.GroupLayout jp_login1Layout = new javax.swing.GroupLayout(jp_login1);
        jp_login1.setLayout(jp_login1Layout);
        jp_login1Layout.setHorizontalGroup(
            jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_login1Layout.createSequentialGroup()
                .addGroup(jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_login1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_llave)
                            .addComponent(txt_user, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txt_pass)))
                    .addGroup(jp_login1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(btn_guardar)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jp_login1Layout.setVerticalGroup(
            jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_login1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jp_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_llave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btn_guardar)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jd_login1Layout = new javax.swing.GroupLayout(jd_login1.getContentPane());
        jd_login1.getContentPane().setLayout(jd_login1Layout);
        jd_login1Layout.setHorizontalGroup(
            jd_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(jd_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_login1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp_login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jd_login1Layout.setVerticalGroup(
            jd_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
            .addGroup(jd_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_login1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp_login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jd_login2.setMinimumSize(new java.awt.Dimension(720, 520));

        jLabel4.setText("Contraseña");

        txt_user1.setEditable(false);
        txt_user1.setText("xxxGranAtuinxxx");

        jLabel5.setText("Usuario");

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_ayuda.setText("Ayuda");
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_login2Layout = new javax.swing.GroupLayout(jd_login2.getContentPane());
        jd_login2.getContentPane().setLayout(jd_login2Layout);
        jd_login2Layout.setHorizontalGroup(
            jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_login2Layout.createSequentialGroup()
                .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_login2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_user1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txt_pass2)))
                    .addGroup(jd_login2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btn_ingresar)
                        .addGap(90, 90, 90)
                        .addComponent(btn_ayuda)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jd_login2Layout.setVerticalGroup(
            jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_login2Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jd_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ingresar)
                    .addComponent(btn_ayuda))
                .addGap(70, 70, 70))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Nombre MundoDisco");

        btn_guardarMundo.setText("Guardar");
        btn_guardarMundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarMundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel6)
                        .addGap(53, 53, 53)
                        .addComponent(txt_mundo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btn_guardarMundo)))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_mundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(btn_guardarMundo)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear MundoDisco", jPanel1);

        jLabel7.setText("MundoDisco");

        jLabel8.setText("Nombre");

        jLabel9.setText("Energia Vital");

        jLabel10.setText("Numero Max. años");

        jLabel11.setText("Region");

        jLabel12.setText("Cantidad Esp. Vivas");

        jLabel13.setText("Objetos");

        btn_guardarCriatura.setText("Guardar");
        btn_guardarCriatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCriaturaActionPerformed(evt);
            }
        });

        rb_1.setText("objeto1");

        rb2.setText("objeto2");

        rb3.setText("objeto3");

        rb4.setText("objeto4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cb_mundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_energia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nombreCriatura, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_años, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_region, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_especies, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_1)
                                            .addComponent(rb3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb4)
                                            .addComponent(rb2)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(btn_guardarCriatura)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(txt_especies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombreCriatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_1)
                                    .addComponent(rb2))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb4)
                                    .addComponent(rb3))))))
                .addGap(6, 6, 6)
                .addComponent(btn_guardarCriatura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Criaturas a MundoDisco", jPanel2);

        ta_1.setColumns(20);
        ta_1.setRows(5);
        jScrollPane1.setViewportView(ta_1);

        btn_buscarMundo.setText("Buscar Mundo Disco");
        btn_buscarMundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarMundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscarMundo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_buscarMundo)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mostrar MundoDisco", jPanel3);

        jLabel14.setText("seleccionar Mundo a Eliminar Criaturas");

        btn_eliminarCriatura.setText("Eliminar");
        btn_eliminarCriatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarCriaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14)
                        .addGap(44, 44, 44)
                        .addComponent(cb_mundos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(btn_eliminarCriatura)))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_mundos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addComponent(btn_eliminarCriatura)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Criaturas", jPanel5);

        jLabel16.setText("MundoDisco");

        jLabel17.setText("Nombre");

        jLabel18.setText("Energia Vital");

        jLabel19.setText("Numero Max. años");

        jLabel20.setText("Region");

        jLabel21.setText("Cantidad Esp. Vivas");

        jLabel22.setText("Objetos");

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        rb_2.setText("objeto1");

        rb5.setText("objeto2");

        rb6.setText("objeto3");

        rb7.setText("objeto4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(cb_mundos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel18))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_energia1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nombreCriatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_años1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_region1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel19))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_especies1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_2)
                                            .addComponent(rb6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb7)
                                            .addComponent(rb5)))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(btn_modificar)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mundos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)
                            .addComponent(txt_especies1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombreCriatura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(txt_region1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel22)
                        .addComponent(txt_energia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_2)
                            .addComponent(rb5))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_años1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb7)
                            .addComponent(rb6))))
                .addGap(17, 17, 17)
                .addComponent(btn_modificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Elementos de un mundo Disco", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        MundoDisco md = new MundoDisco("./credenciales.txt");
        String user;
        user=txt_user.getText();
        pass=txt_pass.getText();
        llave = Integer.parseInt(txt_llave.getText());
        try {
            md.crearCredenciales(user, pass, llave);
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Credenciales Guardadas Correctamente");
        jd_login1.setVisible(false);
        jd_login2.setVisible(true);//hace visible el login2
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
        txt_pass2.setText("");
        ArrayList <Integer> minusculas = new ArrayList();
        ArrayList <Integer> mayusculas = new ArrayList();
        for (int i = 65; i < 91; i++) {
            mayusculas.add(i);
        }
        for (int i = 97; i < 123; i++) {
            minusculas.add(i);
        }
        for (int i = 0; i < pass.length(); i++) {
            char letra = pass.charAt(i);
            int let = (int) letra;
            int suma = let+llave;
            if (let>=65 && let<=90){//si la letra es mayuscula
                if (suma>90){
                    suma = suma-90;
                    suma = suma+96;
                }
            }
            else if (let>=97 && let<=122){//si es minuscula
                if (suma>122){
                    suma = suma-122;
                    suma = suma+64;
                }
            }
            //System.out.println(suma);
            char letra2= (char) suma;
            pass2+=letra2;
        }
        txt_pass2.setText(pass2);
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
        if (txt_pass2.getText().equals(pass2)){
            JOptionPane.showMessageDialog(this, "Usuario Autenticado Correctamente");
            jd_login2.setVisible(false);
            estado=1;
        }
        else{
            JOptionPane.showMessageDialog(this, "Contraseña Incorrecta");
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    public void registro(){
        int op=0;
        if (estado==0){
            op = JOptionPane.showConfirmDialog(this, "Debe iniciar sesion primero");
        }
        //System.out.println("op: " + op);
    }
    private void btn_guardarMundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarMundoActionPerformed
        // TODO add your handling code here:
        registro();
        if (estado==1){
            File archivo=null;
            FileWriter fw = null;
            BufferedWriter bw = null;
            try{
                String nombre = "./";
                nombre+=txt_mundo.getText();
                nombre+=".txt";
                archivo = new File(nombre);
                fw = new FileWriter(archivo,true);//si no escribo true reemplaza el archivo existente por uno nuevo, por default viene "False"
                bw = new BufferedWriter(fw);
            } catch (Exception e){
                e.printStackTrace();
            }
            try {
                bw.close();//siempre 1ero se cierra el buffer 
            } catch (IOException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                fw.close();//fin escritura
            } catch (IOException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
            mundos.add(txt_mundo.getText());
            JOptionPane.showMessageDialog(this,"Mundo creado exitosamente");            
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_mundos.getModel();
            DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cb_mundos1.getModel();
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_mundos2.getModel();
            modelo.addElement(txt_mundo.getText());
            modelo1=modelo;
            modelo2=modelo;
            cb_mundos.setModel(modelo);
            cb_mundos1.setModel(modelo1);
            cb_mundos2.setModel(modelo2);
            txt_mundo.setText("");
//            System.out.println("mundos : " + mundos);
        }
    }//GEN-LAST:event_btn_guardarMundoActionPerformed

    private void btn_guardarCriaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCriaturaActionPerformed
        // TODO add your handling code here:
        registro();
        String direccion = "./";
        direccion+=cb_mundos.getSelectedItem().toString();
        direccion+=".txt";
//        System.out.println("direccion: " + direccion);
        MundoDisco md = new MundoDisco(direccion);
                
        String nombre, energia, años, region, especies;
        ArrayList <String> objetos = new ArrayList();
        if (rb_1.isSelected()){
            objetos.add("objeto1");
        }
        if (rb2.isSelected()){
            objetos.add("Objeto2");
        }
        if (rb3.isSelected()){
            objetos.add("Objeto3");
        }
        if (rb4.isSelected()){
            objetos.add("Objeto4");
        }
        
        nombre = txt_nombreCriatura.getText();
        energia = txt_energia.getText();
        años = txt_años.getText();
        region = txt_region.getText();
        especies = txt_especies.getText();
        Criatura c = new Criatura(nombre, energia, años, region, especies);
        c.setObjetos(objetos);
        
        md.getCriaturas().add(c);
        try {
            md.agregarCriatura();
            //fin Agregar
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Criatura agregada exitosamente a " + cb_mundos.getSelectedItem().toString());
        txt_nombreCriatura.setText("");
        txt_energia.setText("");
        txt_años.setText("");
        txt_region.setText("");
        txt_especies.setText("");
    }//GEN-LAST:event_btn_guardarCriaturaActionPerformed

    private void btn_buscarMundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarMundoActionPerformed
        // TODO add your handling code here:
        registro();
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        ta_1.setText("");
        try{
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto", "txt");
            FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Imagenes", "jpg", "png", "bmp");
            jfc.setFileFilter(filtro);
            jfc.addChoosableFileFilter(filtro2);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION){
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                ta_1.setText("");
                while((linea=br.readLine())!=null){
                    ta_1.append(linea);
                    ta_1.append("\n");
                }
            }//fin if
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            br.close();
            fr.close();
        }catch(IOException ex){
            
        }
    }//GEN-LAST:event_btn_buscarMundoActionPerformed

    private void btn_eliminarCriaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarCriaturaActionPerformed
        // TODO add your handling code here:
        registro();
        System.out.println("");
        String direccion = "./";
        direccion+=cb_mundos1.getSelectedItem().toString();
        direccion+=".txt";
//        System.out.println("direccion: " + direccion);
        MundoDisco md = new MundoDisco(direccion);
        
        try {
            md.eliminarCriaturas();
            //fin Agregar
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Criaturas eliminadas exitosamente de  " + cb_mundos.getSelectedItem().toString());                          
    }//GEN-LAST:event_btn_eliminarCriaturaActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        registro();
        System.out.println("");
        String direccion = "./";
        direccion+=cb_mundos2.getSelectedItem().toString();
        direccion+=".txt";
//        System.out.println("direccion: " + direccion);
        MundoDisco md = new MundoDisco(direccion);
                
        String nombre, energia, años, region, especies;
        ArrayList <String> objetos = new ArrayList();
        if (rb_2.isSelected()){
            objetos.add("objeto1");
        }
        if (rb5.isSelected()){
            objetos.add("Objeto2");
        }
        if (rb6.isSelected()){
            objetos.add("Objeto3");
        }
        if (rb7.isSelected()){
            objetos.add("Objeto4");
        }
        
        nombre = txt_nombreCriatura1.getText();
        energia = txt_energia1.getText();
        años = txt_años1.getText();
        region = txt_region1.getText();
        especies = txt_especies1.getText();
        Criatura c = new Criatura(nombre, energia, años, region, especies);
        c.setObjetos(objetos);
        
        md.getCriaturas().add(c);
        try {
            md.modificarCriatura();
            //fin Agregar
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Criaturas de " + cb_mundos.getSelectedItem().toString() + " Modificadas Exitosamente");
        txt_nombreCriatura.setText("");
        txt_energia.setText("");
        txt_años.setText("");
        txt_region.setText("");
        txt_especies.setText("");
    }//GEN-LAST:event_btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ayuda;
    private javax.swing.JToggleButton btn_buscarMundo;
    private javax.swing.JButton btn_eliminarCriatura;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardarCriatura;
    private javax.swing.JButton btn_guardarMundo;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cb_mundos;
    private javax.swing.JComboBox<String> cb_mundos1;
    private javax.swing.JComboBox<String> cb_mundos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_login1;
    private javax.swing.JDialog jd_login2;
    private javax.swing.JPanel jp_login1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JTextArea ta_1;
    private javax.swing.JTextField txt_años;
    private javax.swing.JTextField txt_años1;
    private javax.swing.JTextField txt_energia;
    private javax.swing.JTextField txt_energia1;
    private javax.swing.JTextField txt_especies;
    private javax.swing.JTextField txt_especies1;
    private javax.swing.JTextField txt_llave;
    private javax.swing.JTextField txt_mundo;
    private javax.swing.JTextField txt_nombreCriatura;
    private javax.swing.JTextField txt_nombreCriatura1;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_pass2;
    private javax.swing.JTextField txt_region;
    private javax.swing.JTextField txt_region1;
    private javax.swing.JTextField txt_user;
    private javax.swing.JTextField txt_user1;
    // End of variables declaration//GEN-END:variables
}
